### ISSUE TITLE
CommandException on /st quit

### ISSUE THREAD

**Issue by SlimeDog** [MartenM/ServerTutorialPlus#2]
Spigot 1.13.1 latest
STP 1.19.0

When I try to quit the tutorial, after being locked in place with the [previous error](https://github.com/MartenM/ServerTutorialPlus/issues/1), I get another exception.

The CommandException needs to be caught and handled appropriately.

```
[23:03:12 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'st' in plugin ServerTutorialPlus v1.19.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.1.jar-2018-10-04-0610:git-Spigot-f6a273b-02518f9]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.1.jar-2018-10-04-0610:git-Spigot-f6a273b-02518f9]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot-1.13.1.jar-2018-10-04-0610:git-Spigot-f6a273b-02518f9]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646) ~[spigot-1.13.1.jar-2018-10-04-0610:git-Spigot-f6a273b-02518f9]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.13.1.jar-2018-10-04-0610:git-Spigot-f6a273b-02518f9]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.1.jar-2018-10-04-0610:git-Spigot-f6a273b-02518f9]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.1.jar-2018-10-04-0610:git-Spigot-f6a273b-02518f9]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.1.jar-2018-10-04-0610:git-Spigot-f6a273b-02518f9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.1.jar-2018-10-04-0610:git-Spigot-f6a273b-02518f9]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.1.jar-2018-10-04-0610:git-Spigot-f6a273b-02518f9]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.1.jar-2018-10-04-0610:git-Spigot-f6a273b-02518f9]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar-2018-10-04-0610:git-Spigot-f6a273b-02518f9]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar-2018-10-04-0610:git-Spigot-f6a273b-02518f9]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at nl.martenm.servertutorialplus.points.custom.ClickBlockPoint$1.stop(ClickBlockPoint.java:107) ~[?:?]
        at nl.martenm.servertutorialplus.objects.TutorialController.stopController(TutorialController.java:112) ~[?:?]
        at nl.martenm.servertutorialplus.objects.TutorialController.cancel(TutorialController.java:89) ~[?:?]
        at nl.martenm.servertutorialplus.commands.ServerTutorialCommands.onCommand(ServerTutorialCommands.java:412) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.1.jar-2018-10-04-0610:git-Spigot-f6a273b-02518f9]
        ... 15 more
```

**Comment by SlimeDog** [comment]
Possible explanation: I played
> /st playpoint tutorialName 1

I was unable to quit from the single point. STP is now in a state that I cannot click on any point or quit. There must be a datum somewhere that is preventing it.

**Comment by MartenM** [comment]
ClickBlockPoint.java:107 references to:
` animationTask.cancel();`
So this issue is the same as the previous one. Should not be too hard to fix.

**Comment by SlimeDog** [comment]
Thanks.
