### ISSUE TITLE
Title Error

### ISSUE THREAD

**Issue by PlayingDude** [MartenM/ServerTutorialPlus#31]
Hey! Got an error when I tried using this command. Did I use the wrong command or something?

#[18:18:35] [Server thread/INFO]: PlayingDude issued server command: /st editpoint tutorial 1 title title
[18:18:35] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'st' in plugin ServerTutorialPlus v1.21.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:git-Paper-243]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[server.jar:git-Paper-243]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[server.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1804) ~[server.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1612) ~[server.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[server.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[server.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[server.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[server.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[server.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[server.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[server.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[server.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[server.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[server.jar:git-Paper-243]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[server.jar:git-Paper-243]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
	at nl.martenm.servertutorialplus.points.editor.args.TitleArg.run(TitleArg.java:37) ~[?:?]
	at nl.martenm.servertutorialplus.points.editor.PointEditor.execute(PointEditor.java:31) ~[?:?]
	at nl.martenm.servertutorialplus.commands.ServerTutorialCommands.onCommand(ServerTutorialCommands.java:720) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Paper-243]
	... 17 more

**Comment by RedstoneFuture** [comment]
For the protocol: I can no longer replicate the bug. Now it cleans the Config entry.

```
        title:
          title: ''
```

**Comment by MartenM** [comment]
Closed due to being 4 years old at this point. Probably fixed.
