### ISSUE TITLE
Title/Playsound/firework bug

### ISSUE THREAD

**Issue by squeaky2137** [MartenM/ServerTutorialPlus#52]
In my tutorial the fireworks do not happen. The playsound does not work ENTITY_PLAYER_LEVELUP and the title / subtitle doesn’t appear 
## Steps to Reproduce

1.download plugin and add to server and startup
2.make a tutorial
3. Add a firework. Title. And playsound ENTITY_PLAYER_LEVELUP to the first point
4.play tutorial

**Comment by MartenM** [comment]
Please included any errors that show in the console. Also what server
version are you on?

Op do 15 jul. 2021 19:33 schreef squeaky2137 ***@***.***>:

**Comment by squeaky2137** [comment]
[10:03:08] [Server thread/INFO]: _Squeaky2137 issued server command: /st play tutorial
1094
[10:03:08] [Server thread/INFO]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.PacketPlayOutTitle
1095
[10:03:08] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getConstructor(java.lang.Class[])" because the return value of "nl.martenm.servertutorialplus.helpers.NeedsReflection.getNMSClass(String)" is null
1096
[10:03:08] [Server thread/WARN]:    at nl.martenm.servertutorialplus.helpers.NeedsReflection.sendTitle(NeedsReflection.java:29)
1097
[10:03:08] [Server thread/WARN]:    at nl.martenm.servertutorialplus.points.ServerTutorialPoint.playDefault(ServerTutorialPoint.java:188)
1098
[10:03:08] [Server thread/WARN]:    at nl.martenm.servertutorialplus.points.ServerTutorialPoint$1.start(ServerTutorialPoint.java:81)
1099
[10:03:08] [Server thread/WARN]:    at nl.martenm.servertutorialplus.objects.TutorialController.start(TutorialController.java:78)
1100
[10:03:08] [Server thread/WARN]:    at nl.martenm.servertutorialplus.commands.ServerTutorialCommands.onCommand(ServerTutorialCommands.java:392)
1101
[10:03:08] [Server thread/WARN]:    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
1102
[10:03:08] [Server thread/WARN]:    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
1103
[10:03:08] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
1104
[10:03:08] [Server thread/WARN]:    at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2170)
1105
[10:03:08] [Server thread/WARN]:    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1981)
1106
[10:03:08] [Server thread/WARN]:    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962)
1107
[10:03:08] [Server thread/WARN]:    at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
1108
[10:03:08] [Server thread/WARN]:    at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
1109
[10:03:08] [Server thread/WARN]:    at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
1110
[10:03:08] [Server thread/WARN]:    at net.minecraft.server.TickTask.run(TickTask.java:18)
1111
[10:03:08] [Server thread/WARN]:    at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
1112
[10:03:08] [Server thread/WARN]:    at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
1113
[10:03:08] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
1114
[10:03:08] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
1115
[10:03:08] [Server thread/WARN]:    at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
1116
[10:03:08] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
1117
[10:03:08] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
1118
[10:03:08] [Server thread/WARN]:    at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
1119
[10:03:08] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
1120
[10:03:08] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
1121
[10:03:08] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
1122
[10:03:08] [Server thread/WARN]:    at java.base/java.lang.Thread.run(Thread.java:831)






this error repeats every time you go to a dif point ( this error is to do with title I believe)

I’m using 1.17.10 or whatever the newest version is on paper and I am using newest plugin version

**Comment by squeaky2137** [comment]
This server is running Paper version git-Paper-100 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 70ea1b2)

And 1.22.0 jar file

**Comment by MartenM** [comment]
Currently on vacation but this indeed a bug. I will try to update once I get back from vacation.

**Comment by MartenM** [comment]
Fixed by commit a6374c059632574c20a7a55afea12a60d304797d
Please let me know if there are any other issues.
