### ISSUE TITLE
BUG - error on console in 1.18.1

### ISSUE THREAD

**Issue by CloudeLecaw** [MartenM/ServerTutorialPlus#64]
```
01:37:25 INFO]: Cloude_Lecaw issued server command: /bank
[01:37:25 WARN]: java.lang.NoSuchMethodException: no such method: net.minecraft.server.network.PlayerConnection.sendPacket(Packet)void/invokeVirtual
[01:37:25 WARN]:        at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:976)
[01:37:25 WARN]:        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117)
[01:37:25 WARN]:        at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3649)
[01:37:25 WARN]:        at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2680)
[01:37:25 WARN]:        at ServerTutorialPlus_1.23.3.jar//com.cryptomorin.xseries.ReflectionUtils.<clinit>(ReflectionUtils.java:108)
[01:37:25 WARN]:        at ServerTutorialPlus_1.23.3.jar//com.cryptomorin.xseries.messages.Titles.<clinit>(Titles.java:76)
[01:37:25 WARN]:        at ServerTutorialPlus_1.23.3.jar//nl.martenm.servertutorialplus.points.ServerTutorialPoint.playDefault(ServerTutorialPoint.java:188)
[01:37:25 WARN]:        at ServerTutorialPlus_1.23.3.jar//nl.martenm.servertutorialplus.points.ServerTutorialPoint$1.start(ServerTutorialPoint.java:81)
[01:37:25 WARN]:        at ServerTutorialPlus_1.23.3.jar//nl.martenm.servertutorialplus.objects.TutorialController.start(TutorialController.java:78)
[01:37:25 WARN]:        at ServerTutorialPlus_1.23.3.jar//nl.martenm.servertutorialplus.commands.sub.tutorials.PlayTutorialCommand.onCommand(PlayTutorialCommand.java:78)
[01:37:25 WARN]:        at ServerTutorialPlus_1.23.3.jar//nl.martenm.simplecommands.RootCommand.onCommand(RootCommand.java:92)
[01:37:25 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[01:37:25 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[01:37:25 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897)
[01:37:25 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2271)
[01:37:25 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2082)
[01:37:25 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2063)
[01:37:25 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[01:37:25 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[01:37:25 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[01:37:25 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[01:37:25 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[01:37:25 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[01:37:25 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[01:37:25 WARN]:        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[01:37:25 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[01:37:25 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[01:37:25 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[01:37:25 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[01:37:25 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[01:37:25 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[01:37:25 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[01:37:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:37:25 WARN]: Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.server.network.PlayerConnection.sendPacket(net.minecraft.network.protocol.Packet)'
[01:37:25 WARN]:        at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
[01:37:25 WARN]:        at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085)
[01:37:25 WARN]:        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
[01:37:25 WARN]:        ... 31 more
```

Here is the tutorial for Bank:
```
  Bank:
    stats:
      plays: 210
    invisible: false
    permission: false
    block-chat: false
    blocks-commands: false
    rewards: []
    command-whitelist: []
    points:
      '0':
        type: TIMED
        location: world 28.0 64.0 335.0 -200.0 15.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        title:
          title: '&2$$$&6Die Bank&2$$$'
          subtitle: '&4Folge den Partikeln'
          fade-in: 20
          stay: 40
          fade-out: 20
      '1':
        type: CHECKPOINT
        location: world 26.0 64.0 327.0 -189.0 12.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: false
        guidecolour: 244 244 244
      '2':
        type: CHECKPOINT
        location: world 19.0 64.0 321.0 -270.0 7.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: false
        guidecolour: 244 244 244
      '3':
        type: CHECKPOINT
        location: world 4.0 64.0 320.0 -269.0 1.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: false
        guidecolour: 244 244 244
      '4':
        type: CHECKPOINT
        location: world -7.0 64.0 321.0 0.0 7.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        title:
          title: '&2$$$&6Die Bank&2$$$'
          subtitle: '&4Ziel erreicht'
          fade-in: 20
          stay: 40
          fade-out: 20
        sound:
          sound: ENTITY_PLAYER_LEVELUP
          pitch: 5.0
          volume: 3.0
        fireworks:
          '0':
            location: world -6.693874693973302 64.0 321.0835682931668 -346.2976 -1.1998975
            meta:
              ==: ItemMeta
              meta-type: FIREWORK
              firework-effects:
              - ==: Firework
                flicker: false
                trail: false
                colors:
                - ==: Color
                  RED: 222
                  BLUE: 42
                  GREEN: 207
                - ==: Color
                  RED: 59
                  BLUE: 26
                  GREEN: 81
                - ==: Color
                  RED: 102
                  BLUE: 211
                  GREEN: 137
                - ==: Color
                  RED: 179
                  BLUE: 44
                  GREEN: 49
                fade-colors: &id001 []
                type: BALL
              power: 1
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: false
        guidecolour: 244 244 244
```

**Comment by MartenM** [comment]
Should be resolved with the latest version.
Please check it out and report if the issue has been fixed: https://www.spigotmc.org/resources/server-tutorial-plus.37741/update?update=438826
