### ISSUE TITLE
NullPointerException when creating and saving tutorial in another world

### ISSUE THREAD

**Issue by 8qBITs** [MartenM/ServerTutorialPlus#71]
read bellow

Error when starting server plugin wont work

java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getName()" because the return value of "org.bukkit.Location.getWorld()" is null
at nl.martenm.servertutorialplus.helpers.PluginUtils.fromLocation(PluginUtils.java:92) ~[ServerTutorialPlus-1.24.5.jar:?]
at nl.martenm.servertutorialplus.points.ServerTutorialPoint.saveData(ServerTutorialPoint.java:261) ~[ServerTutorialPlus-1.24.5.jar:?]
at nl.martenm.servertutorialplus.ServerTutorialPlus.saveTutorials(ServerTutorialPlus.java:295) ~[ServerTutorialPlus-1.24.5.jar:?]
at nl.martenm.servertutorialplus.ServerTutorialPlus.onDisable(ServerTutorialPlus.java:177) ~[ServerTutorialPlus-1.24.5.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:402) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:585) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:562) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.disablePlugins(CraftServer.java:545) ~[purpur-1.19.2.jar:git-Purpur-1839]
at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:956) ~[purpur-1.19.2.jar:git-Purpur-1839]
at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:848) ~[purpur-1.19.2.jar:git-Purpur-1839]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1239) ~[purpur-1.19.2.jar:git-Purpur-1839]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1839]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

## Steps to Reproduce

1. Create tutorial in another world
2. play tutorial and restart server

**Comment by MartenM** [comment]
How do you create these worlds? Or are they just the vanilla ones?

Op zo 4 dec. 2022 12:27 schreef 8qBIT ***@***.***>:

**Comment by 8qBITs** [comment]
Using this plugin https://www.spigotmc.org/resources/myworlds.39594/ its normal overworld.
