### ISSUE TITLE
Some Servertutorials create an error in console

### ISSUE THREAD

**Issue by CloudeLecaw** [MartenM/ServerTutorialPlus#73]
This happens since we updated to paper 1.20.1
```
[00:19:19 INFO]: xenorio issued server command: /farmwelt
>....[00:19:19 WARN]: java.lang.NoSuchFieldException: no such field: net.minecraft.server.level.EntityPlayer.b/net.minecraft.server.network.PlayerConnection/getField
>....[00:19:19 WARN]: 	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:978)
>....


[00:19:19 WARN]: 	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3641)
>....
[00:19:19 WARN]: 	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117)
>....[00:19:19 WARN]: 	at java.base/java.lang.invoke.MethodHandles$Lookup.findGetter(MethodHandles.java:3019)
>....

[00:19:19 WARN]: 	at ServerTutorialPlus_1.24.5.jar//com.cryptomorin.xseries.ReflectionUtils.<clinit>(ReflectionUtils.java:106)
>....
[00:19:19 WARN]: 	at ServerTutorialPlus_1.24.5.jar//com.cryptomorin.xseries.messages.Titles.<clinit>(Titles.java:73)
>....
[00:19:19 WARN]: 	at ServerTutorialPlus_1.24.5.jar//nl.martenm.servertutorialplus.points.ServerTutorialPoint.playDefault(ServerTutorialPoint.java:184)
>....
[00:19:19 WARN]: 	at ServerTutorialPlus_1.24.5.jar//nl.martenm.servertutorialplus.points.ServerTutorialPoint$1.start(ServerTutorialPoint.java:79)
>....

at ServerTutorialPlus_1.24.5.jar//nl.martenm.servertutorialplus.objects.TutorialController.start(TutorialController.java:78)
>....[00:19:19 WARN]: 	[00:19:19 WARN]: 	at ServerTutorialPlus_1.24.5.jar//nl.martenm.simplecommands.RootCommand.onCommand(RootCommand.java:92)
>....[00:19:19 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>....

[00:19:19 WARN]: 	at ServerTutorialPlus_1.24.5.jar//nl.martenm.servertutorialplus.commands.sub.tutorials.PlayTutorialCommand.onCommand(PlayTutorialCommand.java:82)
>....
[00:19:19 WARN]: 	at CMI_9.6.1.1.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1160)
>....
[00:19:19 WARN]: 	at CMI_9.6.1.1.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1054)
>....
[00:19:19 WARN]: 	

[00:19:19 WARN]: 	at CMI_9.6.1.1.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:146)
>....[00:19:19 WARN]: 	at CMI_9.6.1.1.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:150)
>....
[00:19:19 WARN]: 	at CMI_9.6.1.1.jar//com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:193)
>....at CMI_9.6.1.1.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:231)
>....
[00:19:19 WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor703.execute(Unknown Source)
>....
[00:19:19 WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
>....
[00:19:19 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
>....
[00:19:19 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>....
[00:19:19 WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
>....
[00:19:19 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
>....
[00:19:19 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
>....
[00:19:19 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2275)
>....
[00:19:19 WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2259)
>....
[00:19:19 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
>....
[00:19:19 WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
>....
[00:19:19 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
>....
[00:19:19 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
>....
[00:19:19 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
>....
[00:19:19 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1339)
>....
[00:19:19 WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
>....
[00:19:19 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
>....
[00:19:19 WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1316)
>....
[00:19:19 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1309)
>....
[00:19:19 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
>....
[00:19:19 WARN]: 	at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1287)
>....
[00:19:19 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1175)
>....
[00:19:19 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
>....
[00:19:19 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
>....
[00:19:19 WARN]: Caused by: java.lang.NoSuchFieldError: b
>....
[00:19:19 WARN]: 	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
>....
[00:19:19 WARN]: 	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085)
>....
[00:19:19 WARN]: 	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
>....
[00:19:19 WARN]: 	... 40 more
```

Here the Tut from the tutfile
```
  Farmwelt:
    stats:
      plays: 1480
    invisible: false
    permission: false
    block-chat: false
    blocks-commands: false
    rewards: []
    command-whitelist: []
    points:
      '0':
        type: TIMED
        location: world 32.0 64.0 340.0 -175.0 12.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        title:
          title: §2Die Farmwelt
          subtitle: §4Folge den Partikeln
          fade-in: 20
          stay: 40
          fade-out: 20
        sound:
          sound: ENTITY_PLAYER_LEVELUP
          pitch: 5.0
          volume: 3.0
      '1':
        type: CHECKPOINT
        location: world 29.0 64.0 336.0 -204.0 6.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        sound:
          sound: ENTITY_PLAYER_LEVELUP
          pitch: 5.0
          volume: 3.0
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: false
        guidecolour: 244 244 244
      '2':
        type: CHECKPOINT
        location: world 26.0 64.0 326.0 -188.0 7.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        sound:
          sound: ENTITY_PLAYER_LEVELUP
          pitch: 5.0
          volume: 3.0
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: false
        guidecolour: 244 244 244
      '3':
        type: CHECKPOINT
        location: world 20.0 64.0 321.0 -268.0 5.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        sound:
          sound: ENTITY_PLAYER_LEVELUP
          pitch: 5.0
          volume: 3.0
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: false
        guidecolour: 244 244 244
      '4':
        type: CHECKPOINT
        location: world 3.0 64.0 321.0 -269.0 4.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        sound:
          sound: ENTITY_PLAYER_LEVELUP
          pitch: 5.0
          volume: 3.0
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: false
        guidecolour: 244 244 244
      '5':
        type: CHECKPOINT
        location: world -12.0 64.0 320.0 -267.0 -2.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        sound:
          sound: ENTITY_PLAYER_LEVELUP
          pitch: 5.0
          volume: 3.0
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: false
        guidecolour: 244 244 244
      '6':
        type: CHECKPOINT
        location: world -26.0 64.0 319.0 -267.0 -2.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        sound:
          sound: ENTITY_PLAYER_LEVELUP
          pitch: 5.0
          volume: 3.0
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: false
        guidecolour: 244 244 244
      '7':
        type: CHECKPOINT
        location: world -29.0 64.0 311.0 -188.0 6.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        sound:
          sound: ENTITY_PLAYER_LEVELUP
          pitch: 5.0
          volume: 3.0
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: false
        guidecolour: 244 244 244
      '8':
        type: CHECKPOINT
        location: world -29.0 64.0 300.0 -180.0 13.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        sound:
          sound: ENTITY_PLAYER_LEVELUP
          pitch: 5.0
          volume: 3.0
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: false
        guidecolour: 244 244 244
      '9':
        type: CHECKPOINT
        location: world -30.0 63.0 291.0 -186.0 13.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        sound:
          sound: ENTITY_PLAYER_LEVELUP
          pitch: 5.0
          volume: 3.0
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: false
        guidecolour: 244 244 244
      '10':
        type: CHECKPOINT
        location: world -43.0 63.0 291.0 -273.0 5.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        sound:
          sound: ENTITY_PLAYER_LEVELUP
          pitch: 5.0
          volume: 3.0
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: false
        guidecolour: 244 244 244
      '11':
        type: CHECKPOINT
        location: world -54.0 63.0 295.0 -290.0 8.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        sound:
          sound: ENTITY_PLAYER_LEVELUP
          pitch: 5.0
          volume: 3.0
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: false
        guidecolour: 244 244 244
      '12':
        type: CHECKPOINT
        location: world -67.0 63.0 294.0 -271.0 10.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        sound:
          sound: ENTITY_PLAYER_LEVELUP
          pitch: 5.0
          volume: 3.0
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: false
        guidecolour: 244 244 244
      '13':
        type: CHECKPOINT
        location: world -73.0 63.0 302.0 -322.0 6.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        sound:
          sound: ENTITY_PLAYER_LEVELUP
          pitch: 5.0
          volume: 3.0
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: false
        guidecolour: 244 244 244
      '14':
        type: CHECKPOINT
        location: world -75.0 63.0 312.0 -2.0 -1.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        sound:
          sound: ENTITY_PLAYER_LEVELUP
          pitch: 5.0
          volume: 3.0
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: false
        guidecolour: 244 244 244
      '15':
        type: CHECKPOINT
        location: world -75.0 63.0 312.0 -2.0 -1.0
        time: 2.0
        locplayer: false
        locview: false
        messages: []
        commands: []
        title:
          title: §2Die Farmwelt
          subtitle: §4Ziel erreicht
          fade-in: 20
          stay: 40
          fade-out: 20
        sound:
          sound: ENTITY_PLAYER_LEVELUP
          pitch: 5.0
          volume: 3.0
        fireworks:
          '0':
            location: world -75.13971418085254 63.0 312.32799457456605 -359.05002
              -2.7000031
            meta:
              ==: ItemMeta
              meta-type: FIREWORK
              firework-effects:
              - ==: Firework
                flicker: false
                trail: false
                colors:
                - ==: Color
                  ALPHA: 255
                  RED: 222
                  BLUE: 42
                  GREEN: 207
                - ==: Color
                  ALPHA: 255
                  RED: 59
                  BLUE: 26
                  GREEN: 81
                - ==: Color
                  ALPHA: 255
                  RED: 102
                  BLUE: 211
                  GREEN: 137
                - ==: Color
                  ALPHA: 255
                  RED: 179
                  BLUE: 44
                  GREEN: 49
                fade-colors: []
                type: BALL
              power: 1
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: false
        guidecolour: 244 244 244
```

**Comment by CloudeLecaw** [comment]
Edit: The erro in log only arppears sometimes... so im not sure what accactly os causing it.

**Comment by MartenM** [comment]
Please try the latest updated version! It should hopefully fix these issues.
